default:
  api_url: https://hubeau.eaufrance.fr/api
  api_docs: api-docs
  user_agent: https://github.com/inrae/hubeau
  apis:
    prelevements:
      path: v1/prelevements
    indicateurs_services:
      path: v0/indicateurs_services
    hydrometrie:
      path: v1/hydrometrie
    niveaux_nappes:
      path: v1/niveaux_nappes
    poisson:
      path: v1/etat_piscicole
    ecoulement:
      path: v1/ecoulement
    hydrobio:
      path: v1/hydrobio
    temperature:
      path: v1/temperature
    qualite_eau_potable:
      path: v1/qualite_eau_potable
    qualite_nappes:
      path: v1/qualite_nappes
