default:
  api_url: https://hubeau.eaufrance.fr/api
  apis:
    prelevements:
      path: v1/prelevements
      endpoints:
        points_prelevement:
          path: referentiel/points_prelevement
          fields:
           - code_bdlisa
           - code_bss_point_eau
           - code_commune_insee
           - code_departement
           - code_entite_hydro_cours_eau
           - code_entite_hydro_plan_eau
           - code_mer_ocean
           - code_nature
           - code_ouvrage
           - code_point_prelevement
           - code_type_milieu
           - code_zone_hydro
           - date_exploitation
           - fields
           - libelle_departement
           - nappe_accompagnement
           - nom_commune
           - nom_point_prelevement
        chroniques:
          path: chroniques
          fields:
            - annee
            - bbox
            - code_commune_insee
            - code_departement
            - code_mode_obtention_volume
            - code_ouvrage
            - code_qualification_volume
            - code_statut_instruction
            - code_statut_volume
            - code_usage
            - distance
            - fields
            - latitude
            - libelle_departement
            - longitude
            - nom_commune
            - prelevement_ecrasant
            - producteur_donnee
            - volume_max
            - volume_min
        ouvrages:
          path: referentiel/ouvrages
          fields:
            - bbox
            - code_bdlisa
            - code_commune_insee
            - code_departement
            - code_entite_hydro_cours_eau
            - code_entite_hydro_plan_eau
            - code_mer_ocean
            - code_ouvrage
            - code_type_milieu
            - codes_points_prelevements
            - date_exploitation
            - distance
            - fields
            - latitude
            - libelle_departement
            - longitude
            - nom_commune
            - nom_ouvrage
    indicateurs_services:
      path: v0/indicateurs_services
      endpoints:
        communes:
          path: communes
          fields:
            - annee
            - code_commune
            - code_departement
            - detail_service
            - fields
            - type_service
        indicateurs:
          path: indicateurs
          fields:
            - annee
            - code_indicateur
            - fields
        services:
          path: services
          fields:
            - annee
            - code_commune
            - code_departement
            - fields
            - type_service
    hydrometrie:
      path: v1/hydrometrie
      endpoints:
        stations:
          path: referentiel/stations
          fields:
            - bbox
            - code_commune_station
            - code_cours_eau
            - code_departement
            - code_region
            - code_sandre_reseau_station
            - code_site
            - code_station
            - date_fermeture_station
            - date_ouverture_station
            - distance
            - en_service
            - fields
            - latitude
            - libelle_cours_eau
            - libelle_site
            - libelle_station
            - longitude
        sites:
          path: referentiel/sites
          fields:
            - bbox
            - code_commune_site
            - code_cours_eau
            - code_departement
            - code_region
            - code_site
            - code_troncon_hydro_site
            - code_zone_hydro_site
            - distance
            - fields
            - latitude
            - libelle_cours_eau
            - libelle_site
            - longitude
        observations_tr:
          path: observations_tr
          fields:
            - bbox
            - code_entite
            - cursor
            - date_debut_obs
            - date_fin_obs
            - distance
            - fields
            - grandeur_hydro
            - latitude
            - longitude
            - timestep
        obs_elab:
          path: obs_elab
          fields:
            - bbox
            - code_entite
            - cursor
            - date_debut_obs_elab
            - date_fin_obs_elab
            - distance
            - fields
            - grandeur_hydro_elab
            - latitude
            - longitude
            - resultat_max
            - resultat_min
    niveaux_nappes:
      path: v1/niveaux_nappes
      endpoints:
        chroniques:
          path: chroniques
          fields:
            - code_bss
            - date_debut_mesure
            - date_fin_mesure
            - fields
        chroniques_tr:
          path: chroniques_tr
          fields:
            - bbox
            - bss_id
            - code_bss
            - date_debut_mesure
            - date_fin_mesure
            - fields
            - niveau_ngf_max
            - niveau_ngf_min
            - profondeur_max
            - profondeur_min
        stations:
          path: stations
          fields:
            - bbox
            - bss_id
            - code_bdlisa
            - code_bss
            - code_commune
            - code_departement
            - codes_masse_eau_edl
            - date_recherche
            - fields
            - srid
    etat_piscicole:
      path: v1/etat_piscicole
      endpoints:
        observations:
          path: observations
          fields:
            - code_operation
            - date_operation
            - etat_avancement_operation
            - code_qualification_operation
            - libelle_qualification_operation
            - code_station
            - libelle_station
            - uri_station
            - coordonnee_x_station
            - coordonnee_y_station
            - code_epsg_projection_station
            - code_projection_station
            - libelle_projection_station
            - code_point_prelevement
            - code_point_prelevement_aspe
            - libelle_point_prelevement_aspe
            - coordonnee_x_point_prelevement
            - coordonnee_y_point_prelevement
            - code_epsg_projection_point_prelevement
            - code_projection_point_prelevement
            - libelle_projection_point_prelevement
            - lieu_dit_point_prelevement
            - localisation_precise_point_prelevement
            - longitude
            - code_entite_hydro
            - latitude
            - libelle_entite_hydro
            - uri_entite_hydro
            - code_commune
            - libelle_commune
            - code_departement
            - libelle_departement
            - code_region
            - libelle_region
            - code_bassin
            - libelle_bassin
            - codes_dispositifs_collecte
            - libelles_dispositifs_collecte
            - uris_dispositifs_collecte
            - protocole_peche
            - objectifs_operation
            - code_prelevement_elementaire
            - type_prelevement_elementaire
            - duree_prelevement_elementaire
            - numero_passage
            - type_points
            - nombre_points
            - nombre_points_sans_poisson
            - nombre_points_facies_courant
            - nombre_points_facies_plat
            - nombre_points_facies_profond
            - nombre_points_annexes
            - nombre_points_berge
            - nombre_points_chenal
            - nom_ambiance
            - longueur_ambiance
            - largeur_ambiance
            - profondeur_ambiance
            - code_facies_ambiance
            - libelle_facies_ambiance
            - situation_ambiance
            - localisation_ambiance
            - classe_vitesse_courant_ambiance
            - code_ombrage_ambiance
            - libelle_ombrage_ambiance
            - code_granulo_ambiance_dominant
            - libelle_granulo_ambiance_dominant
            - code_granulo_ambiance_accessoire
            - libelle_granulo_ambiance_accessoire
            - vegetation_ambiance
            - abondance_cache_vegetation_aquatique_ambiance
            - abondance_cache_embacles_ambiance
            - abondance_cache_vegetation_bordure_ambiance
            - abondance_cache_sous_berge_ambiance
            - abondance_cache_granulo_ambiance
            - observation_ambiance
            - code_lot
            - code_type_lot
            - libelle_type_lot
            - effectif_lot
            - code_taxon
            - code_alternatif_taxon
            - nom_commun_taxon
            - nom_latin_taxon
            - uri_taxon
            - taille_min_lot
            - taille_max_lot
            - type_longueur_lot
            - poids_lot_mesure
            - poids_lot_estime
            - methode_estimation_poids_lot
            - code_individu
            - taille_individu
            - type_longueur_individu
            - mesure_individu_reelle
            - poids_individu_mesure
            - poids_individu_estime
            - methode_estimation_poids_individu
            - sexe_individu
            - age_individu
            - codes_pathologies_lot
            - libelles_pathologies_lot
            - codes_fractions_pathologies_lot
            - libelles_fractions_pathologies_lot
            - uris_fractions_pathologies_lot
            - importances_pathologies_lot
            - codes_pathologies_individu
            - libelles_pathologies_individu
            - codes_fractions_pathologies_individu
            - libelles_fractions_pathologies_individu
            - uris_fractions_pathologies_individu
            - importances_pathologies_individu

